function pathlist {
    param (
        [string]$Path,
        [int]$IndentLevel = 0,
        [string]$OutputFile = "KengTree.txt"
    )

    # Get all items (files and directories) in the current directory
    $items = Get-ChildItem -Path $Path

    foreach ($item in $items) {
        # If it's a file with .cpp, .hpp, .exe, .mdf, .ndf, .cdf, .bmp, or .png extension
        if (-not $item.PSIsContainer -and $item.Name -match '\.(cpp|hpp|exe|mdf|ndf|cdf|bmp|png|udf|o|py|rc|md|ttf|jpg)$') {
            "{0}{1}" -f ('    ' * $IndentLevel), $item.Name | Out-File -FilePath $OutputFile -Append
        }
        # If it's a directory
        elseif ($item.PSIsContainer) {
            # Display the directory name with tab based on the current indent level
            "{0}{1}" -f ('    ' * $IndentLevel), $item.Name | Out-File -FilePath $OutputFile -Append
            # If the directory is 'pkgconfig' under 'src', handle its contents specially
            if ($item.Name -eq 'pkgconfig' -and $Path -like "*\src") {
                pathlist -Path $item.FullName -IndentLevel ($IndentLevel + 1) -OutputFile $OutputFile
            } else {
                # Recursively call the function to list contents of the subdirectory
                pathlist -Path $item.FullName -IndentLevel ($IndentLevel + 1) -OutputFile $OutputFile
            }
        }
    }
}

# Call the function and specify the directory to start and output file
# Existing content in KengTree.txt will be cleared
"Path Listing Generated by Pathlist Function" | Out-File -FilePath "bin/KengTree.txt"
pathlist -Path (Get-Location) -OutputFile "KengTree.txt"
