function pathlist {
    param (
        [string]$Path,
        [int]$IndentLevel = 0
    )

    # Get all items (files and directories) in the current directory
    $items = Get-ChildItem -Path $Path

    foreach ($item in $items) {
        # If it's a file with .cpp, .hpp, or .exe extension
        if (-not $item.PSIsContainer -and $item.Name -match '\.(cpp|hpp|exe|mdf|ndf|cdf|bmp|png)$') {
            Write-Output ("{0}{1}" -f ('    ' * $IndentLevel), $item.Name)
        }
        # If it's a directory
        elseif ($item.PSIsContainer) {
            # Display the directory name with tab based on the current indent level
            Write-Output ("{0}{1}" -f ('    ' * $IndentLevel), $item.Name)
            # If the directory is 'pkgconfig' under 'src', handle its contents specially
            if ($item.Name -eq 'pkgconfig' -and $Path -like "*\src") {
                pathlist -Path $item.FullName -IndentLevel ($IndentLevel + 1)
            } else {
                # Recursively call the function to list contents of the subdirectory
                pathlist -Path $item.FullName -IndentLevel ($IndentLevel + 1)
            }
        }
    }
}

# Call the function to list contents starting from the specified directory (adjust as needed)
# Generated By Chat-GPT
pathlist -Path (Get-Location)
