#include <SDL2/SDL.h>
#include <iostream>
#include "../auxf/definitions.aux"

#ifndef CAMERA
/**
 * @brief Camera module for the screen movement
 */
#define CAMERA

typedef struct camera{
    SDL_Rect rect;
    float zoom;
}camera;

/**
 * @brief Camera initialisation 
 * 
 * @returns The created camera object
 */
camera init_camera(void);

/**
 * @brief Camera Movement
 * 
 * @param cam Reference to camera
 * @param e Event type
 * 
 * @warning Generated By Chat-GPT (Couldn't be bothered to do the mathematics behind the logic)
 */
void handle_camera(camera& cam, SDL_Event e);

#endif
